CREATE SCHEMA IF NOT EXISTS lead;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'crm_lead_user') THEN
    CREATE ROLE crm_lead_user LOGIN PASSWORD 'crm_lead_dev_password';
  END IF;
END
$$;

GRANT USAGE, CREATE ON SCHEMA lead TO crm_lead_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA lead GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crm_lead_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA lead GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO crm_lead_user;
