CREATE SCHEMA IF NOT EXISTS work;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'crm_work_user') THEN
    CREATE ROLE crm_work_user LOGIN PASSWORD 'crm_work_dev_password';
  END IF;
END
$$;

GRANT USAGE, CREATE ON SCHEMA work TO crm_work_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA work GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crm_work_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA work GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO crm_work_user;
